name: Dispatch action on another repository
description: Trigger `repository_dispatch` event on another repository

inputs:
  github_token:
    required: true
    description: github app token
  event-type:
    required: true
    description: repository-dispatch event type

runs:
  using: composite

  steps:
    - name: Trigger sync on another repo
      run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/PersonaClick/demo-android/dispatches \
        -f "event_type=${{inputs.event-type}}"
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
