name: Persona sync

on:
  workflow_dispatch:

jobs:
  run:
    name: Trigger Synchronization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # - name: Get GitHub App User ID
      #   id: get-user-id
      #   run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      #   env:
      #     GH_TOKEN: ${{ steps.app-token.outputs.token }}
      # - run: |
      #     git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
      #     git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Trigger sync on another repo
        run: |
          # gh workflow run sync-original-repo.yml --repo personaclick/demo-android@master
          # gh repo view personaclick/demo-android
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/PersonaClick/demo-android/dispatches \
          -f "event_type=sync"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
