name: Persona sync

on:
  workflow_dispatch:

jobs:
  run:
    name: Trigger Synchronization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: ls -a -R

      - name: Dispatch action
        uses: ./.github/actions/dispatch
        with:
          appId: ${{ vars.APP_ID }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          owner: personaclick
          repositories: |
            demo-android
