name: Persona sync

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    if: github.event.pull_request.merged == true
    name: Trigger Synchronization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: ls -a -R

      - name: Dispatch action
        uses: ./.github/actions/dispatch
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: personaclick
          repositories: demo-android
          event-type: sync
