name: Persona sync

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    if: github.event.pull_request.merged == true
    name: Trigger Synchronization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: personaclick
          repositories: demo-android

      - name: Dispatch action
        uses: ./.github/actions/dispatch
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          event-type: sync
