name: Persona sync

on:
  workflow_dispatch:

jobs:
  run:
    name: Trigger Synchronization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: personaclick
          # repositories: |
          #   demo-android

      - name: Trigger sync on another repo
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/PersonaClick/demo-android/dispatches \
          -f "event_type=sync"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
